Ping msg
VTAstrobotics/Robot-2017 pull request #16
Opened 2017-04-23 18:28 UTC by jwade109

Adds communication between drive_node and test_controller: drive_node regularly publishes Status messages to /robot/status, and must recieve an Int8 message atleast once every 2 seconds via /driver/ping or it will shut down until it does.

2017-04-27 04:00 UTC, anidev requested changes
Why did you change the launch files - they should probably be changed back, since each launch file is meant to be standalone, so the test launch needs to launch both drive_node as well as test. Also, the main launch file shouldn't have `-pc -debug -aut`, those are just for testing.

2017-04-27 04:00 UTC, anidev commented on src/robot2017/src/drive_node.cpp
> +    ros::Publisher fake_ping = nh.advertise<std_msgs::Bool>("/driver/ping", 100);
Doesn't look like this is necessary anymore

2017-04-27 04:00 UTC, anidev commented on src/robot2017/src/drive_node.cpp
> -
You also removed the subscriptions for teleop and autonomy - should add them back

2017-04-27 04:00 UTC, anidev commented on src/robot2017/src/drive_node.cpp
> +        if (timeSince > 2 && !hibernating)
Could you replace the 2 with a constant int at the top of the file

2017-04-27 04:00 UTC, anidev commented on src/robot2017/src/drive_node.cpp
> +        publishStatus();
It doesn't look you're actually setting the values for the status message anywhere before publishing

2017-05-01 04:40 UTC, jwade109 commented on src/robot2017/src/drive_node.cpp
> -
resolved. not sure why I removed them.

2017-05-01 04:40 UTC, jwade109 commented on src/robot2017/src/drive_node.cpp
> +    ros::Publisher fake_ping = nh.advertise<std_msgs::Bool>("/driver/ping", 100);
correct, that was just for testing. removed

2017-05-01 04:42 UTC, jwade109 commented on src/robot2017/src/drive_node.cpp
> +        publishStatus();
not sure where you want it to be set. I figured there would be something in the ros::ok() loop.

2017-05-25 14:16 UTC, anidev approved these changes

2017-05-25 14:16 UTC, anidev commented
Finally been merged into branch bbb_hw_libraries

2017-05-25 14:16 UTC, merged