Issue #4 - Robot->NUC Feedback
VTAstrobotics/Robot-2017 pull request #9
Opened 2017-03-27 19:30 UTC by mconnervt

I believe this will have fixed all compile errors.

2017-03-28 15:52 UTC, anidev commented
(just adding note) partially resolves #4, waiting for API finish in VESC_BBB_UART

2017-03-28 16:06 UTC, anidev commented on src/robot2017/src/robot_exec.cpp
> +    publishMotors();
Good for now but see if you can call this via a ROS timer so it does not require receiving input from autonomy

2017-03-28 16:07 UTC, anidev requested changes
Compiles fine, however running it fails:

````
[FATAL] [1490717077.957181424]: You must call ros::init() before creating the first NodeHandle
[ERROR] [1490717077.957936877]: [registerPublisher] Failed to contact master at [:0].  Retrying...
````

Also includes error
````
Couldn't find an AF_INET address for []
````
but likely as a result of the above issue.

2017-03-29 03:55 UTC, anidev commented
All right so before merging this, could you run a test on the BeagleBone or a VM? Either change the code temporarily so it calls publishMotors somewhere just for testing, or more ideally change it so publishMotors is called via a ROS timer as I mentioned above.

2017-03-29 13:32 UTC, mconnervt commented
I don't have a VM setup but I can try to get it running on the Beaglebone. Didn't we have a setup where we could test everything on one computer though? Assuming we haven't made any major changes, running test.launch should allow us to see the communication, right? If so, it probably would be simplest to just add a subscriber to the test_controller file that already was publishing teleop commands.

2017-03-29 21:22 UTC, anidev commented
You can use rostopic to see the data being published, but since right now publishMotors is only called when it receives autonomy data you either need to change that or send autonomy data via the test controller.

If you have access to a Linux computer or VM of any sort, you can use docker for testing - I have a docker compose script that will automatically set up and connect two docker containers for testing ROS.

2017-03-30 13:32 UTC, mconnervt commented
No yeah I have a linux setup obviously, but it's dual boot instead of a VM, so I just meant I couldn't use multiple instances of it. I've never used docker before but I doubt it's too difficult, especially if you already have a script setup.

In regards to the MotorFeedback publisher: I agree that its simplest for testing to bypass the whole "autonomy received" part of the program, potentially using the timer feature. But for the final design - will we still want it to be done seperately, or have it be called after autonomy sends a command, since if autonomy isn't active they won't actually need any feedback.

2017-03-30 14:24 UTC, anidev commented
That's a good point though the way it is now, autonomy is always sending us
commands, we just choose to ignore them if not in autonomy mode. So then I
guess it doesn't really matter either way, so for now it's fine the way it
is. I think best solution for testing is have test node send autonomy
commands as well. You could even set it up so it sends a teleop command to
enable autonomy mode so we don't have to hard code autonomy true, just to
test that works too.

On Mar 30, 2017 9:32 AM, "Matthew Conner" <notifications@github.com> wrote:

No yeah I have a linux setup obviously, but it's dual boot instead of a VM,
so I just meant I couldn't use multiple instances of it. I've never used
docker before but I doubt it's too difficult, especially if you already
have a script setup.

In regards to the MotorFeedback publisher: I agree that its simplest for
testing to bypass the whole "autonomy received" part of the program,
potentially using the timer feature. But for the final design - will we
still want it to be done seperately, or have it be called after autonomy
sends a command, since if autonomy isn't active they won't actually need
any feedback.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/VTAstrobotics/Robot-2017/pull/9#issuecomment-290411522>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AA2lx1tAGU4T9zUCN3ulqL6fIki7QQL_ks5rq673gaJpZM4Mqt8x>
.

2017-04-03 23:03 UTC, mconnervt commented
Everything should be done at this point.

2017-04-07 23:54 UTC, anidev approved these changes

2017-04-07 23:55 UTC, anidev commented
Looks good, though could you clean up the info stream messages first before merging

2017-04-10 17:11 UTC, mconnervt commented
Decreased ros rate so that ros logging statements (printed to console) occur less frequently. Obviously we will want to increase the rate again when we are actually testing the autonomy routine.

2017-04-10 17:11 UTC, merged